namespace: mongodb

stack:
  defines: process-group
  runnable-list:
    - mongodb/mongodb
  variables:
    mongo-image-tag: "6.0"
    mongo-express-image-tag: "latest"
    mongodb-init-username: "mongo"
    mongodb-init-password: "password"
    mongodb-init-database: "mongo"