namespace: mongodb-sharded

stack:
  defines: process-group
  runnable-list:
    - mongodb-sharded/mongodb-1
    - mongodb-sharded/mongodb-2
    - mongodb-sharded/mongodb-3 
    - mongodb-sharded/mongodb-init         
    - mongodb-sharded/mongodb-express
  variables:
    mongo-image-tag: "latest"
    mongo-express-image-tag: "latest"
    mongodb-init-username: "mongo"
    mongodb-init-password: "password"
    mongodb-init-database: "mongo"