namespace: mongodb-sharded

stack:
  defines: process-group
  metadata:
    name: Mongodb
    version: latest
    description: |
      MongoDB is a popular open-source NoSQL database management system. It is designed to be scalable and flexible, making it suitable for handling large amounts of unstructured and semi-structured data. 
      MongoDB uses a document-based data model, where data is stored in flexible JSON-like documents that can have varying structures and fields. 
      This allows for greater flexibility and ease of data management, as data can be added, modified, or deleted without the need for predefined schema or migrations.
      Additionally, MongoDB provides various features such as dynamic queries, indexing, replication, and sharding, which make it suitable for a wide range of applications and use cases.
    tags: database, NoSQL, Document-oriented database, Querying, Indexing, Data modeling, JSON, Data analysis, Sharding, Clustering
    website: https://github.com/mongodb/mongo
    source: https://www.mongodb.com/
    publisher: monk.io
    icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA8VbFgxH-i78AZmNqD93mVRkTRd30POqLeCmg9T05ug&s
  runnable-list:
    - mongodb-sharded/mongodb-1
    - mongodb-sharded/mongodb-2
    - mongodb-sharded/mongodb-3
  variables:
    mongo-image-tag: latest
    mongodb-init-username: mongo
    mongodb-init-password: password
    mongodb-init-database: mongo
